apiVersion: v1
kind: Service
metadata:
  name: stock-server-service
spec:
  selector:
    app: stock-server-deployment
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer